[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false

[profile.default.optimizer_details]
# constantOptimizer = true
yul = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config